module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'apps/**/*.(t|j)s',
    'libs/**/*.(t|j)s',
    '!**/*.module.ts',
    '!**/node_modules/**',
    '!**/dist/**',
  ],
  coverageDirectory: './coverage',
  testEnvironment: 'node',
  roots: ['<rootDir>/apps', '<rootDir>/libs'],
  moduleNameMapper: {
    '^@app/common$': '<rootDir>/libs/common/src',
    '^@app/common/(.*)$': '<rootDir>/libs/common/src/$1',
    '^@app/database$': '<rootDir>/libs/database/src',
    '^@app/database/(.*)$': '<rootDir>/libs/database/src/$1',
    '^@app/config$': '<rootDir>/libs/config/src',
    '^@app/config/(.*)$': '<rootDir>/libs/config/src/$1',
    '^@app/messaging$': '<rootDir>/libs/messaging/src',
    '^@app/messaging/(.*)$': '<rootDir>/libs/messaging/src/$1',
    '^@app/auth$': '<rootDir>/libs/auth/src',
    '^@app/auth/(.*)$': '<rootDir>/libs/auth/src/$1',
  },
};
